const JUEGOS = [
  {
    id: "split-fiction",
    titulo: "SPLIT FICTION",
    fecha: "2025-07-18",
    plataformas: ["PS5", "XBOX"],
    genero: ["COOPERATIVO", "AVENTURA"],
    desarrollador: "HAZELIGHT STUDIOS",
    descripcion: "DEL CREADOR DE IT TAKES TWO. AVENTURA COOPERATIVA PARA DOS JUGADORES CON MUNDOS QUE MEZCLAN SCI-FI Y FANTASIA. REQUIERE DOS COPIAS O FRIEND PASS. HISTORIA ORIGINAL Y MECANICAS QUE CAMBIAN CONSTANTEMENTE.",
    trailer: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    gamepass: true,
    psplus: false,
    nuevo: false
  },
  {
    id: "elden-ring-nightreign",
    titulo: "ELDEN RING: NIGHTREIGN",
    fecha: "2025-08-02",
    plataformas: ["PS5", "XBOX"],
    genero: ["RPG", "ACCION", "COOPERATIVO"],
    desarrollador: "FROMSOFTWARE",
    descripcion: "EXPANSION STANDALONE DE ELDEN RING ENFOCADA EN COOPERATIVO PARA TRES JUGADORES. SESIONES DE 40 MINUTOS CON MAPAS ROGUELIKE. NUEVOS JEFES, CLASES Y UN MUNDO EN CONSTANTE CAMBIO.",
    trailer: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    gamepass: false,
    psplus: false,
    nuevo: false
  },
  {
    id: "metroid-prime-4",
    titulo: "METROID PRIME 4: BEYOND",
    fecha: "2025-08-14",
    plataformas: ["SWITCH2"],
    genero: ["ACCION", "AVENTURA"],
    desarrollador: "RETRO STUDIOS",
    descripcion: "REGRESO DE SAMUS ARAN EN LA CUARTA ENTREGA DE LA SAGA PRIME. DISPAROS EN PRIMERA PERSONA, EXPLORACION DE MUNDOS ALIENIGENAS Y NARRATIVA ENVOLVENTE. EXCLUSIVO DE NINTENDO SWITCH 2.",
    trailer: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    gamepass: false,
    psplus: false,
    nuevo: false
  },
  {
    id: "gta-vi",
    titulo: "GRAND THEFT AUTO VI",
    fecha: "2025-09-26",
    plataformas: ["PS5", "XBOX"],
    genero: ["MUNDO ABIERTO", "ACCION"],
    desarrollador: "ROCKSTAR GAMES",
    descripcion: "EL JUEGO MAS ESPERADO DE LA DECADA. AMBIENTADO EN VICE CITY Y ALREDEDORES, CON DOS PROTAGONISTAS: JASON Y LUCIA. MAPA MAS GRANDE DE LA HISTORIA DE LA SAGA Y GRAFICOS GENERACIONALES.",
    trailer: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    gamepass: false,
    psplus: false,
    nuevo: false
  },
  {
    id: "star-fox",
    titulo: "STAR FOX",
    fecha: "2026-06-25",
    plataformas: ["SWITCH2"],
    genero: ["AVENTURA", "ACCION", "SHOOTER"],
    desarrollador: "NINTENDO",
    descripcion: "Star Fox es una aventura llena de acción basada en Star Fox 64 para Nintendo 64. Experimenta nuevos modos de juego (y redescubre los clásicos) mientras te embarcas en una peligrosa misión para salvar el Sistema Lylat, que ahora puedes explorar con mayor detalle gracias a una renovación visual completa del juego. El científico maniático Andross busca el control del sistema estelar Lylat, y solo Fox McCloud y el equipo Star Fox se interponen en su camino. Pilota tu Arwing y recorre el sistema luchando contra fuerzas enemigas y realizando emocionantes maniobras aéreas, como giros y volteretas, para despistar a los enemigos. Encuentra rutas alternativas a través del Sistema Lylat en múltiples partidas, asumiendo nuevas misiones y desafíos variados. Además, únete a tus amigos en el nuevo modo multijugador de batalla de cuatro contra cuatro. Star Fox es una versión cinematográfica del juego Star Fox 64, con diseños de personajes renovados, un aspecto renovado para cada nivel, además de escenas cinemáticas detalladas, diálogos con voces completas y una banda sonora orquestal impresionante. El juego también incluye controles de ratón para los Joy-Con 2 y una nueva función GameChat que te permite ponerte a los mandos de tus personajes favoritos del universo Star Fox.",
    trailer: "https://youtube.com/embed/cWJR_d9gBZ4",
    gamepass: false,
    psplus: false,
    nuevo: true
  },
  {
    id: "namco-legendary-mountains",
    titulo: "NAMCO LEGENDARY MOUNTAINS",
    fecha: "2026-06-25",
    plataformas: ["SWITCH2"],
    genero: ["PUZZLE"],
    desarrollador: "BEXIDE",
    descripcion: "¡Los clásicos arcade de Namco renacen como un puzle 3D! ¡Las leyendas de los 80 regresan con un nuevo estilo! El pixel art clásico se une al 3D: ¡Los icónicos personajes de Namco renacen como vóxeles! ¡El mundo de los legendarios juegos arcade regresa como un puzle 3D! Lanza, apila y fusiona esos vóxeles: ¡busca la máxima puntuación!.",
    trailer: "https://youtube.com/embed/Zx4ejRlUjq0",
    gamepass: false,
    psplus: false,
    nuevo: true
  }
];
