const JUEGOS = [
  {
    id: "the-necromancers-tale",
    titulo: "THE NECROMANCER'S TALE",
    fecha: "2026-06-24",
    plataformas: ["PS5", "XBOX", "SWITCH2"],
    genero: ["RPG", "ISOMETRICO", "GOTICO"],
    desarrollador: "PSYCHIC SOFTWARE",
    descripcion: "The Necromancer's Tale es un RPG narrativo con vista cenital donde encarnas a un noble menor del siglo XVIII, adentrándote en las Artes Oscuras de la Nigromancia en busca de conocimiento y venganza. Un gran poder te espera... junto con lo extraño, lo morboso y un descenso gradual a la locura. Ante ti yace un gran libro de hechizos, repleto de poderosos ritos de muerte y reanimación. ¿Podrás descifrar sus páginas y dominar sus rituales arcanos sin perder la cordura ni ser ahorcado por los habitantes del pueblo? Tu progreso requerirá gran determinación, astucia y discreción. The Necromancer's Tale es un juego con una rica historia, con 400.000 palabras de narrativa y trasfondo, en el que conversarás con más de 180 personajes, cada uno con su propio retrato. Investigarás, negociarás, coaccionarás y halagarás para avanzar en tus objetivos. El sistema de confianza del juego implica que tus decisiones, incluso en las conversaciones, realmente importan. Si la confianza de los habitantes del pueblo cae demasiado bajo, tus decisiones se verán afectadas; si cae aún más bajo, seguramente serás juzgado en un tribunal y ahorcado, o linchado por una turba enfurecida.",
    trailer: "https://www.youtube.com/embed/rticbJlXbLw",
    gamepass: false,
    psplus: false,
    nuevo: true
  },
  {
    id: "deltarune-chapter-5",
    titulo: "DELTARUNE: CHAPTER 5",
    fecha: "2026-06-24",
    plataformas: ["SWITCH2", "PS5"],
    genero: ["INDIE", "RPG"],
    desarrollador: "FANGAMER",
    descripcion: "¡Sumérgete en la historia paralela de UNDERTALE! Lucha o perdona en batallas llenas de acción mientras exploras un mundo misterioso junto a un entrañable elenco de personajes nuevos y conocidos.",
    trailer: "https://youtube.com/embed/n5y22LUfetA",
    gamepass: false,
    psplus: false,
    nuevo: true
  },     
  {
    id: "house-flipper-remastered-collection",
    titulo: "HOUSE FLIPPER REMASTERED COLLECTION",
    fecha: "2026-06-24",
    plataformas: ["XBOX", "PS5"],
    genero: ["INDIE", "SIMULACION"],
    desarrollador: "FROZEN WAY",
    descripcion: "¡Adivina quién ha vuelto, y más brillante que nunca! House Flipper Remastered Collection te permite convertirte en un equipo de renovación unipersonal. ¡Limpia, construye, decora y vende para obtener ganancias! Ahora con mejores gráficos, voces en off, todas las expansiones en una sola caja de herramientas y algunas novedades más entrañables. ¡Es hora de renovar!.",
    trailer: "https://youtube.com/embed/1cDEhGmiSSc",
    gamepass: false,
    psplus: false,
    nuevo: true
  },     
  {
    id: "star-fox",
    titulo: "STAR FOX",
    fecha: "2026-06-25",
    plataformas: ["SWITCH2"],
    genero: ["AVENTURA", "ACCION", "SHOOTER"],
    desarrollador: "NINTENDO",
    descripcion: "Star Fox es una aventura llena de acción basada en Star Fox 64 para Nintendo 64. Experimenta nuevos modos de juego (y redescubre los clásicos) mientras te embarcas en una peligrosa misión para salvar el Sistema Lylat, que ahora puedes explorar con mayor detalle gracias a una renovación visual completa del juego. El científico maniático Andross busca el control del sistema estelar Lylat, y solo Fox McCloud y el equipo Star Fox se interponen en su camino. Pilota tu Arwing y recorre el sistema luchando contra fuerzas enemigas y realizando emocionantes maniobras aéreas, como giros y volteretas, para despistar a los enemigos. Encuentra rutas alternativas a través del Sistema Lylat en múltiples partidas, asumiendo nuevas misiones y desafíos variados. Además, únete a tus amigos en el nuevo modo multijugador de batalla de cuatro contra cuatro. Star Fox es una versión cinematográfica del juego Star Fox 64, con diseños de personajes renovados, un aspecto renovado para cada nivel, además de escenas cinemáticas detalladas, diálogos con voces completas y una banda sonora orquestal impresionante. El juego también incluye controles de ratón para los Joy-Con 2 y una nueva función GameChat que te permite ponerte a los mandos de tus personajes favoritos del universo Star Fox.",
    trailer: "https://youtube.com/embed/cWJR_d9gBZ4",
    gamepass: false,
    psplus: false,
    nuevo: true
  },  
  {
    id: "mousebusters",
    titulo: "MOUSEBUSTERS",
    fecha: "2026-06-25",
    plataformas: ["XBOX"],
    genero: ["AVENTURA", "ACCION"],
    desarrollador: "ODENCAT",
    descripcion: "Acabas de mudarte a tu nuevo hogar y estás emocionado por instalarte… ¡cuando de repente te conviertes en un ratón! Por suerte, pronto conoces a otro roedor que sabe cómo ayudarte. Te pide que lo llames Jefe y te explica que solo hay una forma de romper la maldición: ¡librando a todos los habitantes del edificio de los fantasmas que los atormentan! En cada apartamento encontrarás un fantasma diferente, pero no será fácil encontrarlos. Parece que se alimentan de emociones negativas, así que para desenmascararlos, tendrás que investigar a fondo para descubrir las mayores inseguridades de cada residente. ¡Pero no te dejes atrapar!.",
    trailer: "https://youtube.com/embed/65rMZHqf0VE",
    gamepass: false,
    psplus: false,
    nuevo: true
  },
  {
    id: "flesh-made-fear",
    titulo: "FLESH MADE FEAR",
    fecha: "2026-06-25",
    plataformas: ["PS5"],
    genero: ["HORROR", "ACCION", "INDIE", "SHOOTER"],
    desarrollador: "TAINTED PACT",
    descripcion: "Flesh Made Fear rinde homenaje al survival horror de la era de PSX que definió a una generación. Inspirándose en la trilogía original de Resident Evil, combina magistralmente puzles complejos, combates trepidantes y una atmósfera opresiva. Pero no se trata solo de un guiño nostálgico, sino de una audaz evolución. Controles modernizados, cinemáticas inmersivas y una historia apasionante que te mantendrán en vilo hasta el último momento. Ponte en la piel de un agente de élite del Pelotón de Intervención Reaper (R.I.P.), un grupo de operaciones encubiertas desplegado para neutralizar a Victor The Dripper Ripper, un brillante pero perturbado exagente de la CIA. Sus siniestros experimentos han convertido un pueblo remoto y desolado en una pesadilla plagada de monstruos grotescos y esclavos controlados mentalmente.",
    trailer: "https://youtube.com/embed/etHXbBKo41E",
    gamepass: false,
    psplus: false,
    nuevo: true
  },
  {
    id: "gecko-gods",
    titulo: "GECKO GODS",
    fecha: "2026-06-25",
    plataformas: ["SWITCH2", "PS5"],
    genero: ["AVENTURA", "ACCION", "INDIE", "PLATAFORMA"],
    desarrollador: "INRESIN",
    descripcion: "Gecko Gods te permite controlar a un gecko curioso y adorable con el que escalarás ruinas bañadas por el sol, te abrirás paso por cuevas exuberantes y descubrirás los vestigios de una civilización perdida. Cada camino que tomes te invita a explorar mientras navegas entre islas en tu diminuto barco, cada una con sus propios secretos por descubrir.",
    trailer: "https://youtube.com/embed/Vw2I2y6B2vM",
    gamepass: false,
    psplus: false,
    nuevo: false
  },
  {
    id: "namco-legendary-mountains",
    titulo: "NAMCO LEGENDARY MOUNTAINS",
    fecha: "2026-06-25",
    plataformas: ["SWITCH2"],
    genero: ["PUZZLE"],
    desarrollador: "BEXIDE",
    descripcion: "¡Los clásicos arcade de Namco renacen como un puzle 3D! ¡Las leyendas de los 80 regresan con un nuevo estilo! El pixel art clásico se une al 3D: ¡Los icónicos personajes de Namco renacen como vóxeles! ¡El mundo de los legendarios juegos arcade regresa como un puzle 3D! Lanza, apila y fusiona esos vóxeles: ¡busca la máxima puntuación!.",
    trailer: "https://youtube.com/embed/Zx4ejRlUjq0",
    gamepass: false,
    psplus: false,
    nuevo: true
  },
  {
    id: "monopoly-star-wars-heroes-vs-villains",
    titulo: "MONOPOLY: STAR WARS HEROES VS VILLAINS",
    fecha: "2026-06-30",
    plataformas: ["XBOX", "SWITCH2", "PS5"],
    genero: ["TABLERO"],
    desarrollador: "BEHAVIOUR INTERACTIVE",
    descripcion: "Monopoly: Star Wars Heroes vs. Villains, una versión dinámica y multijugador del juego de mesa familiar favorito de Hasbro, ofrece una experiencia de juego reinventada con momentos cinematográficos, casillas temáticas y elementos dinámicos que hacen que cada partida sea única. Forma equipos con los icónicos héroes y villanos de Star Wars, cada uno con habilidades únicas que pueden influir en la estrategia y cambiar el rumbo del juego a tu favor con cada tirada de dados. El trabajo en equipo y las combinaciones de héroes son clave para la victoria.",
    trailer: "https://youtube.com/embed/VUdjBlPP1I",
    gamepass: false,
    psplus: false,
    nuevo: true
  },
  {
    id: "momento",
    titulo: "MOMENTO",
    fecha: "2026-06-30",
    plataformas: ["XBOX", "SWITCH2", "PS5"],
    genero: ["PUZZLE", "INDIE", "RELAX"],
    desarrollador: "FAT ALIEN CAT",
    descripcion: "Momento es un juego de decoración de habitaciones acogedor con un toque especial: ¡los objetos que elijas alterarán el curso de la historia! Decora tu habitación, elige los objetos que son importantes para ti y descubre cómo estas elecciones influyen a lo largo de tu vida. Empieza en la infancia, seleccionando juguetes que representen tus sueños para el futuro. Sigue esos sueños hasta la edad adulta, explorando escenarios y temas muy diversos. Descubre historias de desamor, asombro y amor, y aprende el significado de los tesoros sentimentales que te acompañarán. Presta mucha atención algunos objetos pueden esconder más de lo que parecen a simple vista. Explora un mundo deliciosamente táctil, enciende luces, hojea libros, acaricia adorables animales y mucho más. Colecciona objetos y muebles en el modo historia para jugar con ellos en el infinito modo creativo. Al final, regresa al principio para descubrir nuevos finales, giros inesperados en el camino y explorar una historia en constante evolución de amor y pérdida.",
    trailer: "https://youtube.com/embed/X1_HJSks2CQ",
    gamepass: false,
    psplus: false,
    nuevo: true
  },
  {
    id: "rv-there-yet",
    titulo: "RV THERE YET?",
    fecha: "2026-06-30",
    plataformas: ["XBOX"],
    genero: ["AVENTURA", "ACCION", "INDIE", "COOP"],
    desarrollador: "NUGGETS ENTERTAINMENT",
    descripcion: "Tú y tus amigos regresan a casa después de unas relajantes vacaciones, pero se ven obligados a tomar una ruta alternativa. Conduzcan su autocaravana por el interior del país y encuentren la salida a la Ruta 65. No todos los que entran al Valle de Mabutts salen con vida. Así que asegúrense de tener siempre a mano hamburguesas, antídotos y el clásico EpiPens. Dominen el cabrestante basado en la física y gánense el derecho a ser el comandante principal del control remoto. Con un cabrestante delantero y otro trasero, su autocaravana está especialmente equipada para pasar por encima, por debajo o a través de la mayoría de los baches.",
    trailer: "https://youtube.com/embed/H7mXFwVNX6Y",
    gamepass: false,
    psplus: false,
    nuevo: true
  },
  {
    id: "deathbulge-battle-of-the-bands",
    titulo: "DEATHBULGE BATTLE OF THE BANDS",
    fecha: "2026-06-30",
    plataformas: ["XBOX", "PS5"],
    genero: ["RPG", "INDIE", "MUSICA"],
    desarrollador: "DEATHBULGE",
    descripcion: "Un juego de rol con temática musical que combina elementos macabros y sádicos. La historia gira en torno a una batalla musical a muerte, donde los participantes pueden atacar y ser atacados con música.",
    trailer: "https://youtube.com/embed/atVHSKXhv30",
    gamepass: false,
    psplus: false,
    nuevo: true
  },
  {
    id: "high-on-life-2",
    titulo: "HIGH ON LIFE 2",
    fecha: "2026-07-01",
    plataformas: ["XBOX", "PS5", "SWITCH2"],
    genero: ["AVENTURA", "ACCION", "MUNDO ABIERTO", "SHOOTER", "FPS"],
    desarrollador: "SQUANCH GAMES",
    descripcion: "Lo has conseguido. Has desmantelado un cártel intergaláctico, rescatado a la humanidad del borde de la extinción y cazado recompensas peligrosas hasta los confines de la galaxia. La caza de recompensas te ha traído fortuna, fama y amor; pero cuando una figura misteriosa de tu pasado reaparece y pone precio a la cabeza de tu hermana, tu cómoda vida se ve sumida en el caos. ¿Tienes lo que se necesita para arriesgarlo todo y acabar con una conspiración intergaláctica que amenaza una vez más a tu especie favorita (los humanos)? High On Life REGRESA mientras tú y tu querido y peculiar equipo de inadaptados alienígenas disparan, apuñalan y patinan a través de mundos hermosos y peligrosos por toda la galaxia para volar por los aires al MALVADO conglomerado farmacéutico empeñado en poner precio a la VIDA HUMANA.",
    trailer: "https://youtube.com/embed/UubdWIkj8Wc",
    gamepass: false,
    psplus: false,
    nuevo: false
  },
  {
    id: "rhythm-heaven-groove",
    titulo: "RHYTHM HEAVEN GROOVE",
    fecha: "2026-07-02",
    plataformas: ["SWITCH2"],
    genero: ["MUSIC"],
    desarrollador: "NINTENDO",
    descripcion: "¡Déjate llevar por el ritmo con la última entrega de la serie Rhythm Heaven, Rhythm Heaven Groove!.",
    trailer: "https://youtube.com/embed/ZdMwqKiSeEE",
    gamepass: false,
    psplus: false,
    nuevo: true
  }
];
